language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gems' ]; then cd .. && eval "mv $currentfolder generator-gems" && cd generator-gems; fi
